### ISSUE TITLE
Hoverfly could not execute this middleware

### ISSUE THREAD

**Issue by KvMadan** [SpectoLabs/hoverfly-java#93] opened 2017-05-10 16:21 UTC
I'm facing below error while using Java as middleware. 
_Hoverfly could not execute this middleware_

Following is the command I'm trying to start. 
_hoverctl middleware --binary java --script C:\tmp\Test.class_

Is Java as middleware supported? Am I using the command incorrectly? or any issue with Java version?

**Comment by tommysitu** [comment] 2017-05-11 11:04
@KvMadan Do you mind sharing your Test.class? I can try debugging it from my end. I am not entirely sure, you may need to pass a packaged jar file to hoverfly.

**Comment by benjih** [comment] 2017-05-11 11:15
@KvMadan @tommysitu 

I am closing this issue as it is a duplicate of https://github.com/SpectoLabs/hoverfly/issues/537.

This issue you have raised is more related to Hoverfly than Hoverfly-Java as its concerning the limitations of middleware within Hoverfly.

**Closed by benjih** 2017-05-11 11:15 UTC
