### ISSUE TITLE
Hoverfly -> verify -> service -> times() sometimes fails

### ISSUE THREAD

**Issue by ttiurani** [SpectoLabs/hoverfly-java#225] opened 2019-11-15 12:27 UTC
## Description of the bug

We're experiencing random failures in hoverfly-java JUnit 5 tester with code like:

```
@ExtendWith(HoverflyExtension.class)
...
    hoverfly.verify(
        service(matches(...))
            .post(...)
            .anyBody()
            .anyQueryParams(),
        times(n));
```

where that `n` hoverfly thinks it has gone is smaller than what it's supposed to be. It seems to be a timing issue, as with slower machines the results are more consistent.

## Steps to reproduce the issue

It is hard to replicate reliably, but happens about 1% of the times on our CI machine with `0.11.5` and almost always on some laptops. But with `0.12.2` of `hoverfly-java` it fails much more frequently on the CI machine too, so much so that we can't upgrade.

What might the cause of this random failures be? This issue is making our tests annoyingly flaky.

**Comment by ttiurani** [comment] 2019-11-18 07:34
This happens with identical POST calls at almost the same time in a threaded environment. Here are the log timestamps from the Java client that all get the correct response body:

```
09:08:23.661
09:08:23.661
09:08:23.662
```

but hoverfly-java says sometimes : "Expected 3 requests ... But actual number of requests is 2". Currently I'm getting this about every fifth test. This happens sometimes with POSTs with three different payloads and sometimes with three identical POSTs. I'm running this with the maven surefire plugin default configuration and can reproduce it by running one test in a loop with a server:

`while mvn surefire:test -Dtest=Test#test ; do :; done`

so it doesn't have anything to do with simultaneous tests on the java-side either. I am configuring Hoverfly with:

```
@HoverflySimulate(
  source =
      @HoverflySimulate.Source(
        type = HoverflySimulate.SourceType.CLASSPATH,
        value = "simulation.json"
      ),
  config = @HoverflyConfig(plainHttpTunneling = true)
)
```

So for some reason when the calls happen at exactly the same time, one of the calls gets lost. That sounds like some concurrency bug in hoverfly, right?

**Comment by ttiurani** [comment] 2019-11-18 09:55
@tommysitu not 100% sure yet, but preliminary tests seems to indicate I was able to fix this with this change:

```
diff --git a/core/journal/journal.go b/core/journal/journal.go
index 7c1bf5e3..985c92ff 100644
--- a/core/journal/journal.go
+++ b/core/journal/journal.go
@@ -4,6 +4,7 @@ import (
        "fmt"
        "net/http"
        "time"
+  "sync"

        sorting "sort"
        "strings"
@@ -50,6 +51,8 @@ func (this *Journal) NewEntry(request *http.Request, response *http.Response, mo
                Body:    string(respBody),
                Headers: response.Header,
        }
+  var l sync.Mutex
+  l.Lock()

        if len(this.entries) >= this.EntryLimit {
                this.entries = append(this.entries[:0], this.entries[1:]...)
@@ -62,6 +65,7 @@ func (this *Journal) NewEntry(request *http.Request, response *http.Response, mo
                TimeStarted: started,
                Latency:     time.Since(started),
        })
+  l.Unlock()

        return nil
 }
```

**Comment by tommysitu** [comment] 2019-11-18 09:59
It does sound like a race condition. A similar problem was reported before for the state store (https://github.com/SpectoLabs/hoverfly/issues/767). 

Do you mind creating a PR?

**Comment by ttiurani** [comment] 2019-11-18 10:51
So adding that mutex does make the problem more rare but I could still get it to happen by the about 30th run when I had 3 requests happen at the same millisecond.

I'll do some more poking.

**Comment by tommysitu** [comment] 2020-02-16 21:30
thank you for the fix! it's being released in `0.12.3`

**Closed by tommysitu** 2020-02-16 21:30 UTC
Labels: bug

**Comment by tejo93** [comment] 2024-03-07 16:43
I am facing this issue again in Hoverfly java version of 0.14.0

Is there any alternative to verify the service called.

**Comment by tommysitu** [comment] 2024-03-07 21:42
@tejo93 could you try upgrading to the latest version?

**Comment by tejo93** [comment] 2024-03-08 17:04
@tommysitu this issue was supposed to be fixed by 0.14.0 and we are currently using that version, to upgrade we would need to wait, can you please confirm if this version ( 0.14,0 ) has the desired fix.

**Comment by tommysitu** [comment] 2024-03-08 17:14
@tejo93 are you sure is the same race condition issue that cause the verification to fail? Because there could be other bugs. You will need to give me a bit info to check if it's the same issue or not. There are other things that could break verification.

**Comment by tejo93** [comment] 2024-03-08 18:03
So in a class I have three test cases for testing different endpoints.
test case 1 --> endpoint 1
test case 2 --> endpoint 2
test case 3 --> endpoint 3

Now I have hoverfly simulation for each endpoint.
I have a hoverfly simulation
```java
hoverfly.simulate(SimulationSource.dsl(
                service(MOCK_SERVER_BASE_URL)
                        .get("endpoint<number>")
                        .queryParam("q","")
                        .willReturn(success().withFixedDelay(3, TimeUnit.SECONDS))
        ));
```
I can see this in the logs 
```java
Response found interface{} cache destination=localhost:7777 key=89fa84fc1073295c8e4efd4adda0feec method=GET path="endpoint<number>" rawQuery={}
Response found interface{} cache destination=localhost:7777 key=89fa84fc1073295c8e4efd4adda0feec method=GET path="endpoint<number>" rawQuery={}
```

when I hit http://localhost:<adminPort>/api/v2/journal , I see two instances of request object.

But when I do verification 
```java
 hoverfly.verify(
                service(MOCK_SERVER_BASE_URL)
                        .get("endpoint<number>)
                        .anyBody(), times(2));
```

It sometimes passes, and sometimes fails.

For now I am doing workaround by calling the journal api and reading that JSON and doing assertion.

**Comment by tommysitu** [comment] 2024-03-09 16:49
Hey @tejo93 thanks for the info. Does it look like the kind of tests you are doing? https://github.com/SpectoLabs/hoverfly-java/pull/299/files

I've run them over 500 times but nothing fails. 
![Screenshot 2024-03-09 at 4 43 57 PM](https://github.com/SpectoLabs/hoverfly-java/assets/7671879/fc365915-f11e-4eb1-b177-04e569341549)

However I'm on the latest version, it would be great to see what you have done differently in your test, if you can reproduce the issue with the above test, that will help me to debug. 

Also try resetting the journal before test to prevent interference: 
```
@Before
    public void setUp() {
        hoverfly.resetJournal();
    }
```

**Comment by tejo93** [comment] 2024-03-09 23:14
Hi @tommysitu  why are you verifying with times (2) when you called the service only once, isn't that the exact issue I pointed out earlier?

**Comment by tommysitu** [comment] 2024-03-09 23:16
It's calling the endpoints twice in each test: https://github.com/SpectoLabs/hoverfly-java/pull/299/files#diff-99f9ae0c8997e70fde30ddc27236a0cf0146a6b9afc930386ca22cb4388bf9baR90-R94

**Comment by tejo93** [comment] 2024-03-10 00:13
Thanks @tommysitu , for clarifying, I apologize for missing the endpoint call.
