### ISSUE TITLE
Premature end of file when simulate no content for second resource for the same base endpoint with maven, surefire but works in intellij.

### ISSUE THREAD

**Issue by rkpandey78** [SpectoLabs/hoverfly-java#202] opened 2019-02-01 22:47 UTC
[Fatal Error] :1:1: Premature end of file.

https://<basePath>/resource1 200 response
https://<basePath>/resoure2  204 no Content

when execution hits resouce2, hoverfly response could not be processed with HttpClient or RestTemplate. 
The problem went away in intellij when I upgraded from 0.11.0 to 0.11.2. but the problem persists when I run tests with maven, and surefire.

**Comment by rkpandey78** [comment] 2019-02-01 22:48
in the class under test resources are access in order, resource1 and resource2 respectively.

**Comment by tommysitu** [comment] 2019-02-06 12:10
From what you describe, it's hard to figure out what went wrong. Could you show me the test class (including the HoverflyRule configs) that fails? I need it to reproduce the error on my end.

**Comment by tommysitu** [comment] 2019-07-23 15:07
Closing this issue due to lack of info

**Closed by tommysitu** 2019-07-23 15:07 UTC
