### ISSUE TITLE
SimulationSource.file reads in wrong encoding

### ISSUE THREAD

**Issue by larsthorup** [SpectoLabs/hoverfly-java#224] opened 2019-11-15 09:22 UTC
## Description of the bug
When using `SimulationSource.file()` to read a previously captured file, the file appears to be read in a different encoding than UTF-8 in which it was written, causing the simulation to be wrong.

## Steps to reproduce the issue
Using this helper function to read my GitHub profile:

    public String getGithubUser() throws Exception {
        CloseableHttpClient httpClient = HttpClients.custom()
                .useSystemProperties() // Note: support Hoverfly
                .build();
        HttpGet httpGet = new HttpGet("https://api.github.com/users/larsthorup");
        httpGet.setHeader(HttpHeaders.ACCEPT_ENCODING, "identity"); // Note: avoid gzip
        CloseableHttpResponse response = httpClient.execute(httpGet);
        InputStream inputStream = response.getEntity().getContent();
        String responseBody = org.apache.commons.io.IOUtils.toString(inputStream, StandardCharsets.UTF_8.toString());
        return responseBody;
    }

and this test to capture the request/response:

    @Test
    public void test_capture() throws Exception {
        Hoverfly hoverfly = new Hoverfly(localConfigs(), HoverflyMode.CAPTURE);
        hoverfly.start();
        String user = getGithubUser();
        System.out.println(user);
        assert(user.contains("\"location\":\"København, Danmark\""));
        hoverfly.exportSimulation(Paths.get("src/test/resources/hoverfly/capture.json"));
        hoverfly.close();
    }

Then this test which simulates the request using the capture file fails:

    @Test
    public void test_simulateFile() throws Exception {
        Hoverfly hoverfly = new Hoverfly(localConfigs(), HoverflyMode.SIMULATE);
        hoverfly.start();
        hoverfly.simulate(SimulationSource.file(Paths.get("src/test/resources/hoverfly/capture.json"    )));
        String user = getGithubUser();
        System.out.println(user);
        assert(user.contains("\"location\":\"København, Danmark\""));
        hoverfly.close();
    }

### Observed result
On my machine the simulated user response instead contains `KÃ¸benhavn, Danmark`

### Expected result
I expect the simulated user response to contain `København, Danmark`

## Additional relevant information
If not indicated above:
1. Hoverfly Java version: 0.12.2, OS: Windows 10, Java version "1.8.0_221"

I am able to work around the problem by extending SimulationSource and overriding getSimulation() to return a String that is read from the file system explicitly specifying UTF-8 as the encoding.

However, this appears to be a bug in Hoverfly Java, so hence this bug report.

**Comment by tommysitu** [comment] 2019-11-15 23:54
Thanks for the detail bug report. Will release a fix early next week.

**Comment by tommysitu** [comment] 2019-11-19 22:51
Couldn't reproduce it on my end as it's a platform-specific problem. I hope this PR will fix it: https://github.com/SpectoLabs/hoverfly-java/pull/227

**Comment by tommysitu** [comment] 2020-02-16 21:30
released in `0.12.3`

**Closed by tommysitu** 2020-02-16 21:30 UTC
Labels: bug
