### ISSUE TITLE
Simulation not triggered using HTTPS + Destination. Bug?

### ISSUE THREAD

**Issue by ambaxter** [SpectoLabs/hoverfly-java#139] opened 2017-09-18 20:56 UTC
Hello,

We're using hoverfly-java to simulate certain services while leaving others untouched. I've found some odd behavior where if we simulate an HTTPs endpoint and use any destination the simulation fails to trigger. The application hits the server Hoverfly should be proxying.

If I remove the destination, the traffic is simulated correctly.
If I keep the destination, but the HTTPS URL protocol with HTTP, the traffic is simulated correctly.

Is this a bug? I've debugged it to the application boundary and I'm not sure how to proceed..

**Comment by ambaxter** [comment] 2017-09-18 21:16
Versions tested: 0.8.0, 0.8.1

**Comment by tommysitu** [comment] 2017-09-19 08:46
Hi @ambaxter, I don't seem to reproduce the problem, the following test goes green for me: 
```
    @Test
    public void shouldSimulateHttpsWithDestinationConfig() throws Exception {
        hoverfly = new Hoverfly(HoverflyConfig.configs().destination("www.my-test.com"), HoverflyMode.SIMULATE);
        hoverfly.start();
        hoverfly.importSimulation(classpath("test-service.json"));

        RestTemplate restTemplate = new RestTemplate();
        final ResponseEntity<String> getBookingResponse = restTemplate.getForEntity("https://www.my-test.com/api/bookings/1", String.class);

        // Then
        assertThat(getBookingResponse.getStatusCode()).isEqualTo(OK);
        assertThatJson(getBookingResponse.getBody()).isEqualTo("{" +
                "\"bookingId\":\"1\"," +
                "\"origin\":\"London\"," +
                "\"destination\":\"Singapore\"," +
                "\"time\":\"2011-09-01T12:30\"," +
                "\"_links\":{\"self\":{\"href\":\"http://localhost/api/bookings/1\"}}" +
                "}");
    }
```

Can you check you are not passing the URI scheme into the destination config?

**Comment by ambaxter** [comment] 2017-09-19 18:03
Hey @tommysitu,

I'm able to get your example working. However, if I modify the destination to be "bookings" it fails the same as in my local environment.

```java
    @Test
    public void shouldSimulateHttpsWithDestinationConfig() throws Exception {
        hoverfly = new Hoverfly(HoverflyConfig.configs().destination("bookings"), HoverflyMode.SIMULATE);
        hoverfly.start();
        hoverfly.importSimulation(classpath("test-service.json"));

        RestTemplate restTemplate = new RestTemplate();
        final ResponseEntity<String> getBookingResponse = restTemplate.getForEntity("https://www.my-test.com/api/bookings/1", String.class);

        // Then
        assertThat(getBookingResponse.getStatusCode()).isEqualTo(OK);
        assertThatJson(getBookingResponse.getBody()).isEqualTo("{" +
                "\"bookingId\":\"1\"," +
                "\"origin\":\"London\"," +
                "\"destination\":\"Singapore\"," +
                "\"time\":\"2011-09-01T12:30\"," +
                "\"_links\":{\"self\":{\"href\":\"http://localhost/api/bookings/1\"}}" +
                "}");
    }
```

**Comment by tommysitu** [comment] 2017-09-19 21:13
The destination should be the hostname, so if you want to simulate this API `https://www.my-test.com/api/bookings/1`, the destination should be set to `www.my-test.com`.

**Comment by ambaxter** [comment] 2017-09-20 14:07
Hm. That makes sense. The term "destination" confused me as I thought that was any part of the URL.

We're using Zuul to front a bunch of our services. This makes them all have the same destination/host - i.e. http://router/service1/v1/endpoint and http://router/service2/v1/endpoint. 

We were using destination to specify "service1" or "service2" so that we only simulate the ones we need simulated leaving the rest accessible. However, since destination is only supposed to be the host we must've hit a bug where that's allowed for http.

Do you have any suggestions?

**Comment by tommysitu** [comment] 2017-09-20 15:25
Yeah, it is usually called the `host`. What you require is effectively the ability to simulate specific endpoints of a host, while allowing all other requests to pass through. It is not supported in Hoverfly yet. I will raise an issue in the core Hoverfly project for someone to look into it.

**Comment by ambaxter** [comment] 2017-09-20 16:09
Thank you!

Through some quirk destination as part of the path works for http endpoints. We can limp along on that until something more permanent comes along. Thank you!

**Comment by tommysitu** [comment] 2017-09-25 21:55
There is an existing hoverfly issue for this feature request: https://github.com/SpectoLabs/hoverfly/issues/389. 
I am closing this issue as it is not a bug.

**Closed by tommysitu** 2017-09-25 21:55 UTC
