### ISSUE TITLE
Runtime Exception when using WildFly Swarm + Hoverfly Java

### ISSUE THREAD

**Issue by lordofthejars** [SpectoLabs/hoverfly-java#68] opened 2017-02-23 09:01 UTC
When running some tests using Hoverfly Java where some other JAXRS provider (like Resteasy in Wildfly Swarm) in classpath you get next exception:

```
java.lang.ExceptionInInitializerError
	at com.sun.jersey.core.spi.factory.MessageBodyFactory.initReaders(MessageBodyFactory.java:182)
	at com.sun.jersey.core.spi.factory.MessageBodyFactory.initReaders(MessageBodyFactory.java:176)
	at com.sun.jersey.core.spi.factory.MessageBodyFactory.init(MessageBodyFactory.java:162)
	at com.sun.jersey.api.client.Client.init(Client.java:343)
	at com.sun.jersey.api.client.Client.access$000(Client.java:119)
	at com.sun.jersey.api.client.Client$1.f(Client.java:192)
	at com.sun.jersey.api.client.Client$1.f(Client.java:188)
	at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
	at com.sun.jersey.api.client.Client.<init>(Client.java:188)
	at com.sun.jersey.api.client.Client.<init>(Client.java:160)
	at com.sun.jersey.api.client.Client.create(Client.java:673)
	at io.specto.hoverfly.junit.core.Hoverfly.<init>(Hoverfly.java:73)
	at io.specto.hoverfly.junit.rule.HoverflyRule.<init>(HoverflyRule.java:93)
	at io.specto.hoverfly.junit.rule.HoverflyRule.inCaptureMode(HoverflyRule.java:142)
	at io.specto.hoverfly.junit.rule.HoverflyRule.inCaptureMode(HoverflyRule.java:131)
	at org.music.ServiceVirtualizationTest.<clinit>(ServiceVirtualizationTest.java:16)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:142)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at org.junit.runners.model.FrameworkField.get(FrameworkField.java:73)
	at org.junit.runners.model.TestClass.getAnnotatedFieldValues(TestClass.java:230)
	at org.junit.runners.ParentRunner.classRules(ParentRunner.java:255)
	at org.junit.runners.ParentRunner.withClassRules(ParentRunner.java:244)
	at org.junit.runners.ParentRunner.classBlock(ParentRunner.java:194)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:362)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.jboss.resteasy.spi.ResteasyProviderFactory
	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:152)
	at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:120)
	at javax.ws.rs.core.MediaType.valueOf(MediaType.java:179)
	at com.sun.jersey.core.header.MediaTypes.<clinit>(MediaTypes.java:65)
	... 38 more
Caused by: java.lang.ClassNotFoundException: org.jboss.resteasy.spi.ResteasyProviderFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at javax.ws.rs.ext.FactoryFinder.newInstance(FactoryFinder.java:114)
	at javax.ws.rs.ext.FactoryFinder.find(FactoryFinder.java:207)
	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:135)
	... 41 more
```

This class of JAXRS providers might happen in other scenarios where for example tests are executed within the container. I suggest ( I can help on that) on changing client from JAXRS to one more neutral implementation like OkHttp + gson/jackson

**Comment by tommysitu** [comment] 2017-02-23 11:57
Hi @lordofthejars, your proposal is quite good, OkHttp is much more lightweight than Jersey client, and less likely to cause dependency conflict for some JAVA EE projects. 

I'd also like to understand the problem as well. Could you have a look at this test using RestEasyClient? 
https://github.com/SpectoLabs/hoverfly-java/blob/resteasy-client/src/test/java/io/specto/hoverfly/ruletest/RestEasyClientTest.java

I couldn't reproduce the error you got.

These are the dependencies I added:

```
testCompile 'org.jboss.resteasy:resteasy-client:3.1.0.Final'
testCompile 'org.jboss.resteasy:resteasy-jaxrs:3.1.0.Final'
```

**Comment by lordofthejars** [comment] 2017-02-23 14:58
Even better, I send you the project :) https://github.com/lordofthejars/composers-unicorn just move this class https://github.com/lordofthejars/composers-unicorn/blob/master/sv/src/test/java/org/music/ServiceVirtualizationTest.java and gradle dependencies to root project and you can execute it. Or in the project you have developed just use Wildfly swarm deps (you can check in my root project how it is done).

**Comment by lordofthejars** [comment] 2017-02-23 15:09
Also as soon as you give me the ok, I'll start the migration to okhttp :)

**Comment by tommysitu** [comment] 2017-02-23 15:14
I can run the test without a problem. Was it supposed to fail?

**Comment by lordofthejars** [comment] 2017-02-23 15:16
if you move the test to root module and not from `sv` module yes :) I am going to try again for just in case

**Comment by lordofthejars** [comment] 2017-02-23 15:22
Yes it happens to me, check this branch https://github.com/lordofthejars/composers-unicorn/tree/allinone test  https://github.com/lordofthejars/composers-unicorn/blob/allinone/src/test/java/org/music/ServiceVirtualizationTest.java

**Comment by tommysitu** [comment] 2017-02-23 15:24
Misunderstood, now I see the problem after moving the test to the root module.

**Comment by lordofthejars** [comment] 2017-02-23 15:25
no prob :)

**Comment by tommysitu** [comment] 2017-02-23 15:38
You probably know better than me on this, it somehow requires 'org.jboss.resteasy:resteasy-jaxrs' to run. As you said it is not desirable for hoverfly-java to introduce unnecessary dependencies to the client code. 

We initially looked at okhttp, we thought it would pull in some Android libraries, but now I realised that it is just provided dependencies. So yes, if you could help migrating the http client, that'll be great!

**Comment by lordofthejars** [comment] 2017-02-23 15:39
Of course, I am going to start working on this.

**Comment by tommysitu** [comment] 2017-02-27 15:31
I've tried the latest snapshot version (0.3.9-SNAPSHOT), it fixed the problem. Thank you for your PR @lordofthejars. Closing this issue now.

**Closed by tommysitu** 2017-02-27 15:31 UTC
Labels: enhancement
